"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-06 12:52:12.609122
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slices',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('height_min_cm', sa.Float(), nullable=True),
    sa.Column('height_max_cm', sa.Float(), nullable=True),
    sa.Column('size_min', sa.Integer(), nullable=True),
    sa.Column('size_max', sa.Integer(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('member_target', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('auth_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('handle', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_founding_seller', sa.Boolean(), nullable=False),
    sa.Column('age_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_account_id', sa.String(length=255), nullable=True),
    sa.Column('slice_id', sa.Uuid(), nullable=True),
    sa.Column('style_vector', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('referral_code', sa.String(length=16), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['slice_id'], ['slices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_auth_subject'), ['auth_subject'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_handle'), ['handle'], unique=True)

    op.create_table('waitlist_entries',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('usual_size', sa.String(length=20), nullable=False),
    sa.Column('slice_id', sa.Uuid(), nullable=True),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referred_by_code', sa.String(length=16), nullable=True),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['slice_id'], ['slices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_waitlist_email'),
    sa.UniqueConstraint('referral_code')
    )
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waitlist_entries_referred_by_code'), ['referred_by_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_waitlist_entries_slice_id'), ['slice_id'], unique=False)

    op.create_table('body_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('usual_size', sa.String(length=20), nullable=True),
    sa.Column('outseam_cm', sa.Float(), nullable=True),
    sa.Column('inseam_cm', sa.Float(), nullable=True),
    sa.Column('rise_cm', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hip_cm', sa.Float(), nullable=True),
    sa.Column('shoulder_cm', sa.Float(), nullable=True),
    sa.Column('torso_length_cm', sa.Float(), nullable=True),
    sa.Column('bust_cm', sa.Float(), nullable=True),
    sa.Column('precision_tier', sa.Enum('estimated', 'measured', 'confirmed', name='precision_tier'), nullable=False),
    sa.Column('source_per_field', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('picker_choices', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('followee_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    op.create_table('listings',
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('bottoms', 'tops', 'dresses', name='category'), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('size_label', sa.String(length=20), nullable=False),
    sa.Column('price_pence', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'live', 'sold', 'removed', name='listing_status'), nullable=False),
    sa.Column('photos', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('relisted_from_order_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_status'), ['status'], unique=False)

    op.create_table('garment_measurements',
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('outseam_cm', sa.Float(), nullable=True),
    sa.Column('inseam_cm', sa.Float(), nullable=True),
    sa.Column('rise_cm', sa.Float(), nullable=True),
    sa.Column('waist_flat_cm', sa.Float(), nullable=True),
    sa.Column('hip_flat_cm', sa.Float(), nullable=True),
    sa.Column('pit_to_pit_cm', sa.Float(), nullable=True),
    sa.Column('shoulder_flat_cm', sa.Float(), nullable=True),
    sa.Column('length_cm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('orders',
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.Column('protection_fee_pence', sa.Integer(), nullable=False),
    sa.Column('shipping_pence', sa.Integer(), nullable=False),
    sa.Column('seller_fee_pence', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_transfer_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'shipped', 'delivered', 'released', 'refunded', name='order_status'), nullable=False),
    sa.Column('tracking_ref', sa.String(length=120), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_release_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_auto_release_at'), ['auto_release_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=False)

    op.create_table('fit_ratings',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('fit_as_described', sa.Boolean(), nullable=False),
    sa.Column('issues', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    with op.batch_alter_table('fit_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fit_ratings_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fit_ratings_seller_id'), ['seller_id'], unique=False)

    op.create_table('payout_events',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount_pence', sa.Integer(), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payout_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_events_order_id'), ['order_id'], unique=False)

    op.create_table('twins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_a_id', sa.Uuid(), nullable=False),
    sa.Column('user_b_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('twins', schema=None) as batch_op:
        batch_op.create_index('ix_twins_pair', ['user_a_id', 'user_b_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_twins_user_a_id'), ['user_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_twins_user_b_id'), ['user_b_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twins_user_b_id'))
        batch_op.drop_index(batch_op.f('ix_twins_user_a_id'))
        batch_op.drop_index('ix_twins_pair')

    op.drop_table('twins')
    with op.batch_alter_table('payout_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_events_order_id'))

    op.drop_table('payout_events')
    with op.batch_alter_table('fit_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fit_ratings_seller_id'))
        batch_op.drop_index(batch_op.f('ix_fit_ratings_buyer_id'))

    op.drop_table('fit_ratings')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_stripe_payment_intent_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_seller_id'))
        batch_op.drop_index(batch_op.f('ix_orders_listing_id'))
        batch_op.drop_index(batch_op.f('ix_orders_buyer_id'))
        batch_op.drop_index(batch_op.f('ix_orders_auto_release_at'))

    op.drop_table('orders')
    op.drop_table('garment_measurements')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_status'))
        batch_op.drop_index(batch_op.f('ix_listings_seller_id'))
        batch_op.drop_index(batch_op.f('ix_listings_category'))

    op.drop_table('listings')
    op.drop_table('follows')
    op.drop_table('body_profiles')
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_slice_id'))
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_referred_by_code'))

    op.drop_table('waitlist_entries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_handle'))
        batch_op.drop_index(batch_op.f('ix_users_auth_subject'))

    op.drop_table('users')
    op.drop_table('slices')
    # ### end Alembic commands ###
